version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
